# File:   connecti4n_server.py
# Author: Ethan Martin & Stefano Coronado
# Date:   28 March 2019
# Brief:  Server for a game of Connect I4n
#
# We hereby declare on our word of honor that we have neither given nor
# received any unauthorized help on this work.

import socket


VERSION = '1.0'


def c4n_message(code, content):
    # Make sure that we have a valid code
    if code not in ['ERROR', 'STOP', 'START', 'MOVE', 'BOARD', 'RESULT']:
        return None

    # Construct the base message
    out = 'C4N ' + VERSION + ' ' + code

    # If we have content to add, append it
    if content != None:
        out += ' ' + str(content)

    # Return generated bytes
    return out.encode()


def main():
    HOST = 'localhost'
    PORT = 4414

    # Create the socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

    # Bind to the desired address
    sock.bind((HOST, PORT))

    # Wait for a client
    sock.listen()
    conn, addr = sock.accept()

    print('New connection from:', addr)

    # Send server full message
    conn.sendall(c4n_message('ERROR', 3))

    # Close the client connection
    conn.close()

    # Close the socket
    sock.close()


main()
